server:
  port: 80

spring:
  application:
    name: semo

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@xci.iptime.org:1521/xepdb1
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sesac_semoi
    password: semoi1111

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    jdbc:
      sqlonly: DEBUG
      resultsettable: DEBUG
      audit: DEBUG
      resultset: DEBUG